[pytest]
testpaths = .
addopts = -v --headed
markers =
    functional: 功能測試 - 驗證功能是否符合規格
    regression: 回歸測試 - 確保舊功能未被破壞
    smoke: 冒煙測試 - 快速驗證核心流程可動

;[pytest]
;# pytest 基本設定
;testpaths = tests
;addopts = -v --headed
